services:
  mysql:
    image: mysql:8.0
    container_name: data-transformer-mysql
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: transformer
      MYSQL_USER: user
      MYSQL_PASSWORD: password
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - transformer-network

  app:
    build:
      context: .
      dockerfile: docker/app/Dockerfile
    container_name: data-transformer-app
    restart: always
    depends_on:
      mysql:
        condition: service_healthy
    environment:
      DB_HOST: mysql
      DB_PORT: 3306
      DB_USER: user
      DB_PASSWORD: password
      DB_NAME: transformer
    expose:
      - "8080"
    deploy:
      resources:
        limits:
          cpus: "4"
          memory: 2G
        reservations:
          cpus: "2"
          memory: 1G
    networks:
      - transformer-network

  haproxy:
    build:
      context: ./docker/haproxy
      dockerfile: Dockerfile
    container_name: data-transformer-haproxy
    restart: always
    ports:
      - "80:80"
      - "8404:8404"
    volumes:
      - ./docker/haproxy/haproxy.cfg:/usr/local/etc/haproxy/haproxy.cfg:ro
    depends_on:
      - app
    networks:
      - transformer-network

networks:
  transformer-network:
    driver: bridge

volumes:
  mysql_data:
